#!/bin/sh

# Configuración básica del entorno
bspc monitor -d I II III IV V

# Comportamiento de las ventanas
bspc config border_width         2
bspc config window_gap           6
bspc config split_ratio          0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config click_to_focus       true

# Reglas opcionales (puedes agregar más si usas apps flotantes)
bspc rule -a Gimp desktop=^2 state=floating
